theme = "tokyonight_storm"

[editor]
line-number = "relative"
bufferline = "always"
scrolloff = 7
auto-save = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# i = ["collapse_selection", "insert_mode"]
# a = ["collapse_selection", "append_mode"]

# lf-pick
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]

# Buffer shortcuts to use them like tabs
C-l = [":buffer-next"]
C-h = [":buffer-previous"]
C-w = [":buffer-close"]

# Alt + j and Alt + k to move up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up",  "paste_before", "collapse_selection"]

[keys.insert]
# Alt + j and Alt + k to move up and down
A-j = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection", "insert_mode"]
A-k = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up",  "paste_before", "collapse_selection", "insert_mode"]

[keys.select]
# Alt + j and Alt + k to move up and down
A-j = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection", "select_mode"]
A-k = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up",  "paste_before", "collapse_selection", "select_mode"]
