import = ["/home/dhain/.config/alacritty/themes/onedark.toml"]

[env]
# Because of ssh
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[window]
opacity = 0.88

[scrolling]
history = 100000
